/**
 * @typedef {{
 *   id: string,
 *   categoryId: string,
 *   labelEn: string,
 *   labelIt: string,
 *   descEn: string,
 *   descIt: string,
 * }} Exercise
 */

/** @type {Exercise[]} */
export const EXERCISES = [
  // ----- Arms -----
  {
    id: "arms-swing-fb",
    categoryId: "arms",
    labelEn: "Swing arms forward and back",
    labelIt: "Braccia avanti e indietro",
    descEn: "Stand tall with soft knees. Swing both arms straight forward to shoulder height, then back past your hips. Keep the neck relaxed and breathe steadily.",
    descIt: "In piedi, ginocchia morbide. Muovi entrambe le braccia dritte avanti fino all’altezza delle spalle, poi indietro oltre i fianchi. Collo rilassato e respiro regolare.",
  },
  {
    id: "arms-lateral-raise",
    categoryId: "arms",
    labelEn: "Lateral arm raises",
    labelIt: "Alzate laterali",
    descEn: "Arms at your sides, palms facing in. Lift both arms out to the sides to shoulder height with a slight bend in the elbows. Lower with control.",
    descIt: "Braccia lungo i fianchi, palmi verso il corpo. Solleva lateralmente fino all’altezza delle spalle con un leggero piega dei gomiti. Abbassa lentamente.",
  },
  {
    id: "arms-alt-punch",
    categoryId: "arms",
    labelEn: "Alternating punches forward",
    labelIt: "Colpi alternati in avanti",
    descEn: "Hands near chest height. Extend one arm forward to shoulder height, palm down, then switch. Keep ribs down and exhale on each punch.",
    descIt: "Mani davanti al petto. Estendi un braccio in avanti all’altezza della spalla, palmo in basso, poi alterna. Costole verso il basso, espira a ogni estensione.",
  },
  {
    id: "arms-cross-swing",
    categoryId: "arms",
    labelEn: "Cross-body arm swings",
    labelIt: "Oscillazioni incrociate",
    descEn: "Swing arms across the torso at shoulder height, alternating which arm crosses in front. Allow a gentle twist through the mid-back.",
    descIt: "Oscilla le braccia incrociando il busto all’altezza delle spalle, alternando chi sta davanti. Concediti una leggera rotazione nella parte alta della schiena.",
  },
  {
    id: "arms-circle-cw",
    categoryId: "arms",
    labelEn: "Arm circles clockwise",
    labelIt: "Cerchi con le braccia (senso orario)",
    descEn: "Extend arms to the sides. Draw smooth circles forward and up, like tracing a hoop. Keep shoulders low away from the ears.",
    descIt: "Braccia tese ai lati. Disegna cerchi grandi in avanti e in alto. Mantieni le spalle abbassate, lontano dalle orecchie.",
  },
  {
    id: "arms-circle-ccw",
    categoryId: "arms",
    labelEn: "Arm circles counter-clockwise",
    labelIt: "Cerchi con le braccia (senso antiorario)",
    descEn: "Same arm position, reverse the circle direction—backward and up. Keep movements controlled, not rushed.",
    descIt: "Stessa posizione delle braccia, inverti il cerchio: indietro e poi su. Movimento controllato, senza affrettarti.",
  },
  {
    id: "arms-wrist-circle",
    categoryId: "arms",
    labelEn: "Wrist circles",
    labelIt: "Cerchi con i polsi",
    descEn: "Arms forward at chest height, elbows soft. Rotate wrists slowly—half the time each direction. Keep shoulders relaxed.",
    descIt: "Braccia avanti all’altezza del petto, gomiti morbidi. Ruota lentamente i polsi; cambia direzione a metà tempo. Spalle rilassate.",
  },
  {
    id: "arms-overhead-reach",
    categoryId: "arms",
    labelEn: "Alternating overhead reaches",
    labelIt: "Allungamenti sopra la testa alternati",
    descEn: "Reach one arm straight up beside your ear, lengthen your side, lower, then switch. Rib cage stays quiet—avoid arching hard.",
    descIt: "Allunga un braccio verso l’alto accanto all’orecchio, allunga il fianco, abbassa e alterna. Evita di inarcare tanto la schiena.",
  },
  {
    id: "arms-chest-opener",
    categoryId: "arms",
    labelEn: "Dynamic chest opener",
    labelIt: "Apertura dinamica del petto",
    descEn: "Clasp hands behind your back or open arms wide, squeeze shoulder blades, release forward gently. Repeat slowly.",
    descIt: "Mani dietro la schiena unite (se puoi) oppure apri le braccia lateralmente, chiudi le scapole indietro, poi torna dolcemente davanti. Ripeti lentamente.",
  },
  {
    id: "arms-floor-skimmer",
    categoryId: "arms",
    labelEn: "Bent-over reverse flies (light)",
    labelIt: "Braccia indietro busto in avanti",
    descEn: "Soft knees, hinge hips slightly, palms facing each other. Open arms out to the sides like spreading wings, pinch shoulder blades, lower slowly.",
    descIt: "Ginocchia morbide, busto leggermente in avanti dai fianchi, palmi che si guardano. Apri le braccia ai lati come ali, stringi le scapole, abbassa lentamente.",
  },

  // ----- Shoulders -----
  {
    id: "shoulders-roll-fwd",
    categoryId: "shoulders",
    labelEn: "Roll shoulders forward",
    labelIt: "Rotolamento spalle in avanti",
    descEn: "Lift shoulders gently up, roll them forward, down, and back. Repeat slowly—think smooth circles, not shrugging hard.",
    descIt: "Solleva leggermente le spalle, ruotale in avanti, giù e indietro. Movimento circolare morbido, senza tirare troppo.",
  },
  {
    id: "shoulders-roll-back",
    categoryId: "shoulders",
    labelEn: "Roll shoulders back",
    labelIt: "Rotolamento spalle indietro",
    descEn: "Lift, roll shoulders backward, down, and forward. Open the chest as you roll back. Keep the jaw soft.",
    descIt: "Solleva, ruota le spalle indietro, giù e avanti. Apri il petto quando torni indietro. Mascella rilassata.",
  },
  {
    id: "shoulders-circle-left",
    categoryId: "shoulders",
    labelEn: "Single-arm circle — left",
    labelIt: "Cerchio con un braccio — sinistro",
    descEn: "Left arm extended to the side or slightly forward. Draw a controlled circle with a straight elbow. Switch direction halfway if you like.",
    descIt: "Braccio sinistro teso di lato o leggermente avanti. Disegna un cerchio controllato con gomito quasi teso. Puoi invertire il senso a metà tempo.",
  },
  {
    id: "shoulders-circle-right",
    categoryId: "shoulders",
    labelEn: "Single-arm circle — right",
    labelIt: "Cerchio con un braccio — destro",
    descEn: "Right arm extended. Circle at shoulder height with steady rhythm. Keep the opposite shoulder relaxed.",
    descIt: "Braccio destro teso. Cerchio all’altezza della spalla, ritmo costante. Spalla opposta rilassata.",
  },
  {
    id: "shoulders-shrug",
    categoryId: "shoulders",
    labelEn: "Shrug and release",
    labelIt: "Spalle su e rilascio",
    descEn: "Lift shoulders toward ears, hold a breath, then drop them fully. Repeat—focus on the release, not the squeeze.",
    descIt: "Porta le spalle verso le orecchie, una breve pausa, poi lasciale cadere. Concentrati sul rilascio.",
  },
  {
    id: "shoulders-blade-squeeze",
    categoryId: "shoulders",
    labelEn: "Shoulder blade squeezes",
    labelIt: "Stringere le scapole",
    descEn: "Arms bent at 90°, elbows tucked. Pull elbows back as if squeezing a pencil between shoulder blades. Release. Repeat.",
    descIt: "Gomiti piegati a novanta gradi vicino ai fianchi. Tira i gomiti indietro come se volessi stringere una matita tra le scapole. Rilascia e ripeti.",
  },
  {
    id: "shoulders-wall-slide-sim",
    categoryId: "shoulders",
    labelEn: "Wall slide (simulated)",
    labelIt: "Scivolata lungo il muro (simulata)",
    descEn: "Back against a wall if you have one; otherwise stand tall. Raise arms in a W shape, slide up toward a Y, lower with control.",
    descIt: "Schiena al muro se puoi; altrimenti busto eretto. Braccia a forma di W, poi slitta verso l’alto quasi a Y, poi ridiscendi con controllo.",
  },
  {
    id: "shoulders-pendulum",
    categoryId: "shoulders",
    labelEn: "Arm pendulums",
    labelIt: "Pendolo delle braccia",
    descEn: "Lean forward slightly, let one arm hang and swing it front-to-back and side-to-side like a pendulum. Switch arms.",
    descIt: "Piega leggermente il busto in avanti, lascia penzolare un braccio e muovilo avanti-indietro e a destra-sinistra come un pendolo. Cambia braccio.",
  },
  {
    id: "shoulders-overhead-shrug",
    categoryId: "shoulders",
    labelEn: "Overhead shrug-down",
    labelIt: "Spalle su con braccia alzate",
    descEn: "Arms in a V overhead. Shrug shoulders up, then press shoulders down away from ears while arms stay up.",
    descIt: "Braccia in V sopra la testa. Solleva le spalle, poi spingi le spalle verso il basso lontano dalle orecchie mantenendo le braccia su.",
  },

  // ----- Jumps -----
  {
    id: "jumps-in-place",
    categoryId: "jumps",
    labelEn: "Jump in place",
    labelIt: "Saltelli sul posto",
    descEn: "Small bouncy hops with feet hip-width. Land softly through the balls of the feet, knees slightly bent. Skip if joints bother you.",
    descIt: "Piccoli saltelli con piedi larghi quanto i fianchi. Atterraggio morbido sulle punte dei piedi, ginocchia piegate. Evita questo esercizio se senti dolore alle articolazioni.",
  },
  {
    id: "jumps-quarter-left",
    categoryId: "jumps",
    labelEn: "Quarter-turn jump left",
    labelIt: "Salto con quarto di giro a sinistra",
    descEn: "Hop and rotate 90° to your left. Land with knees bent. Use arms for balance. Keep jumps small if space is tight.",
    descIt: "Saltello ruotando di novanta gradi a sinistra. Atterra con ginocchia piegate. Usa le braccia per equilibrio. Riduci l’ampiezza se hai poco spazio.",
  },
  {
    id: "jumps-quarter-right",
    categoryId: "jumps",
    labelEn: "Quarter-turn jump right",
    labelIt: "Salto con quarto di giro a destra",
    descEn: "Hop and rotate 90° to the right. Stay light on landing; face forward again on the next rep or alternate as you prefer.",
    descIt: "Saltello ruotando di novanta gradi a destra. Atterraggio leggero; al passo dopo torna di fronte o alterna come preferisci.",
  },
  {
    id: "jumps-half-turn",
    categoryId: "jumps",
    labelEn: "Half-turn jump",
    labelIt: "Salto con mezzo giro",
    descEn: "Jump and spin 180°, landing softly. Use a smaller jump if you feel unstable. Clear space around you first.",
    descIt: "Salta e gira su te stesso di centottanta gradi, atterraggio morbido. Riduci se non sei stabile. Libera lo spazio intorno a te.",
  },
  {
    id: "jumps-jacks",
    categoryId: "jumps",
    labelEn: "Jumping jacks",
    labelIt: "Salti con aperture (forbice)",
    descEn: "Jump feet out as arms lift overhead, then return. Keep a slight bend in knees when landing. Lower impact: step out instead of jump.",
    descIt: "Apri piedi e braccia sopra la testa, poi torna unito. Ginocchia morbide all’atterraggio. Versione più dolce: fai solo il passo laterale senza saltare.",
  },
  {
    id: "jumps-star",
    categoryId: "jumps",
    labelEn: "Star jumps",
    labelIt: "Salti a stella",
    descEn: "Jump legs wide and arms wide like a star at the same time, land softly together. Smaller stars if needed.",
    descIt: "Salta aprendo gambe e braccia come una stella contemporaneamente, poi chiudi morbido. Riduci l’ampiezza se serve.",
  },
  {
    id: "jumps-quiet-hops",
    categoryId: "jumps",
    labelEn: "Quiet landing hops",
    labelIt: "Saltelli silenziosi",
    descEn: "Tiny hops in place focusing on silent landings—absorb through ankles and knees without slamming heels.",
    descIt: "Saltelli minuscoli sul posto: cerca di atterrare il più silenziosamente possibile, ammortizzando con caviglie e ginocchia senza sbattere i talloni.",
  },

  // ----- Knees -----
  {
    id: "knees-high",
    categoryId: "knees",
    labelEn: "High knees in place",
    labelIt: "Ginocchia alte sul posto",
    descEn: "March or jog on the spot, lifting knees toward hip height. Swing opposite arms naturally. Stand tall, avoid leaning far back.",
    descIt: "Marcia leggera o corri sul posto portando le ginocchia verso l’altezza dei fianchi. Muovi le braccia al ritmo opposto alle gambe. Schiena eretta.",
  },
  {
    id: "knees-circle-left",
    categoryId: "knees",
    labelEn: "Knee circles — left leg",
    labelIt: "Cerchi con il ginocchio — gamba sinistra",
    descEn: "Stand on right foot lightly. Bend left knee and draw small circles with the knee cap—half the time each direction if possible.",
    descIt: "Appoggio leggero sul piede destro. Piega il ginocchio sinistro e disegna piccoli cerchi; cambia direzione a metà tempo se puoi.",
  },
  {
    id: "knees-circle-right",
    categoryId: "knees",
    labelEn: "Knee circles — right leg",
    labelIt: "Cerchi con il ginocchio — gamba destra",
    descEn: "Stand on left foot lightly. Circle the bent right knee smoothly. Hold a wall if balance is tricky.",
    descIt: "Appoggio leggero sul piede sinistro. Cerchi fluidi con il ginocchio destro piegato. Tieniti al muro se serve equilibrio.",
  },
  {
    id: "knees-alt-lift",
    categoryId: "knees",
    labelEn: "Alternating knee lifts",
    labelIt: "Sollevamenti alternati delle ginocchia",
    descEn: "Slowly lift one knee to hip height, lower, then switch. Hands can stay on hips or reach forward for balance.",
    descIt: "Solleva lentamente un ginocchio verso l’altezza dell’anca, abbassa e alterna. Mani sui fianchi o avanti per equilibrio.",
  },
  {
    id: "knees-squat-pulse",
    categoryId: "knees",
    labelEn: "Squat pulse",
    labelIt: "Impulsi nella semi-accosciata",
    descEn: "Feet shoulder-width, sit hips back into a half squat. Pulse up and down a few inches. Knees track over toes; chest lifted.",
    descIt: "Piedi alla larghezza delle spalle, seduti indietro in semi-accosciata. Piccoli movimenti su e giù di pochi centimetri. Ginocchia allineati alle punte, petto aperto.",
  },
  {
    id: "knees-butt-kicks",
    categoryId: "knees",
    labelEn: "Butt kicks",
    labelIt: "Talloni verso i glutei",
    descEn: "Jog on the spot bringing heels toward glutes. Quick but light feet; stand tall.",
    descIt: "Corricchi sul posto portando i talloni verso i glutei. Piedi leggeri e veloci ma busto eretto.",
  },
  {
    id: "knees-lateral-drive",
    categoryId: "knees",
    labelEn: "Lateral knee drives",
    labelIt: "Ginocchio verso il lato",
    descEn: "Slow alternating knee lifts out to the side like stepping over a low hurdle. Stay upright.",
    descIt: "Solleva lentamente un ginocchio verso il fianco come per passare un ostacolo basso. Alterna. Resta eretto.",
  },
  {
    id: "knees-tap-back",
    categoryId: "knees",
    labelEn: "Alternating toe taps behind",
    labelIt: "Punta indietro alternata",
    descEn: "Shift weight to one leg; lightly tap the other toes behind you without deep lunges. Switch rhythmically.",
    descIt: "Sposta il peso su una gamba; tocca leggermente il pavimento dietro di te con la punta dell’altra gamba senza affondare troppo. Alterna.",
  },
  {
    id: "knees-slow-march",
    categoryId: "knees",
    labelEn: "Slow controlled march",
    labelIt: "Marcia lenta controllata",
    descEn: "March with exaggerated knee lift but slow tempo—focus on balance at the top of each step.",
    descIt: "Marcia alzando bene il ginocchio ma lentamente; concentrati sull’equilibrio quando la gamba è su.",
  },

  // ----- Full-body / balance -----
  {
    id: "full-twist-left",
    categoryId: "fullBody",
    labelEn: "Torso twist left",
    labelIt: "Rotazione busto a sinistra",
    descEn: "Feet hip-width, arms relaxed or bent at chest. Rotate ribs and shoulders left while hips stay mostly forward. Don’t force the neck.",
    descIt: "Piedi larghi quanto i fianchi. Ruota busto e spalle a sinistra lasciando i fianchi quasi davanti. Non forzare il collo.",
  },
  {
    id: "full-twist-right",
    categoryId: "fullBody",
    labelEn: "Torso twist right",
    labelIt: "Rotazione busto a destra",
    descEn: "Same stance, rotate to the right. Keep knees soft. Move from the mid-back, not just the arms flailing.",
    descIt: "Stessa posizione, ruota a destra. Ginocchia morbide. Il movimento parte dal centro della schiena, non solo dalle braccia.",
  },
  {
    id: "full-side-step",
    categoryId: "fullBody",
    labelEn: "Side step left and right",
    labelIt: "Passo laterale sinistra e destra",
    descEn: "Step out to the left, bring feet together, then out to the right. Stay low and light—like a gentle shuffle warm-up.",
    descIt: "Passo laterale a sinistra, chiudi i piedi, poi passo laterale a destra. Movimento leggero e un po’ basso come riscaldamento.",
  },
  {
    id: "full-heel-toe",
    categoryId: "fullBody",
    labelEn: "Heel-to-toe walk in place",
    labelIt: "Passo tallone-punta sul posto",
    descEn: "Step forward placing heel then toe, tiny steps in place. Focus on balance; use a slower rhythm if needed.",
    descIt: "Passi piccolissimi sul posto: prima appoggia il tallone poi la punta. Concentrati sull’equilibrio; rallenta se serve.",
  },
  {
    id: "full-stand-left",
    categoryId: "fullBody",
    labelEn: "Single-leg stand — left",
    labelIt: "Equilibrio su una gamba — sinistra",
    descEn: "Lift right foot just off the floor. Stand tall on left leg; use a fingertip on a wall if needed. Switch gaze on a fixed point.",
    descIt: "Solleva il piede destro da terra. Stai eretto sulla gamba sinistra; un dito sul muro se serve. Fissa un punto davanti a te.",
  },
  {
    id: "full-stand-right",
    categoryId: "fullBody",
    labelEn: "Single-leg stand — right",
    labelIt: "Equilibrio su una gamba — destra",
    descEn: "Lift left foot slightly. Balance on right leg with relaxed shoulders. Breathe slowly to steady yourself.",
    descIt: "Solleva leggermente il piede sinistro. Equilibrio sulla gamba destra, spalle rilassate. Respira piano per stabilizzarti.",
  },
  {
    id: "full-good-morning",
    categoryId: "fullBody",
    labelEn: "Good morning hinge",
    labelIt: "Piega avanti dai fianchi (leggera)",
    descEn: "Hands on hips or crossed on chest. Soft knees, push hips back, hinge torso forward until you feel hamstrings, stand tall.",
    descIt: "Mani sui fianchi o incrociate sul petto. Ginocchia morbide, spingi i fianchi indietro e piega il busto in avanti fino a sentire leggera tensione dietro le cosce, poi torna su eretto.",
  },
  {
    id: "full-inchworm-partial",
    categoryId: "fullBody",
    labelEn: "Inchworm (partial, standing)",
    labelIt: "Bruco — versione in piedi ridotta",
    descEn: "Fold forward, walk hands out on the floor to plank-feel height if flexible, walk hands back and roll up. Skip deep folds if back is sensitive.",
    descIt: "Piega il busto in avanti, cammina con le mani sul pavimento fino a una posizione piatta se puoi, poi torna con le mani verso i piedi e risali. Evita se la schiena protesta.",
  },
  {
    id: "full-cross-crawl",
    categoryId: "fullBody",
    labelEn: "Cross-crawl march",
    labelIt: "Marcia incrociata ginocchio-gomito",
    descEn: "Lift right knee and touch with left hand across body, alternate. Slow and tall—think coordination, not speed.",
    descIt: "Solleva il ginocchio destro e avvicina il gomito sinistro incrociando sul busto, poi alterna. Lento ed eretto: coordinazione prima della velocità.",
  },
  {
    id: "full-chop-diagonal",
    categoryId: "fullBody",
    labelEn: "Diagonal reach chop",
    labelIt: "Diagonale alto-basso con le braccia",
    descEn: "Reach hands high to one corner, then swing arms down across body to opposite hip like a gentle wood chop. Switch sides.",
    descIt: "Braccia in alto verso un angolo, poi muovi le braccia in diagonale verso l’anca opposta come un taglio leggero. Alterna i lati.",
  },
  {
    id: "full-lateral-reach",
    categoryId: "fullBody",
    labelEn: "Side reaches",
    labelIt: "Allungamenti laterali",
    descEn: "Stand tall, slide one hand down your leg while the other reaches overhead, creating a long side bend. Alternate.",
    descIt: "Eretto, fai scivolare una mano lungo la gamba mentre l’altra braccia si allunga sopra la testa per un lungo piegamento laterale. Alterna.",
  },

  // ----- Dodge / agility -----
  {
    id: "dodge-shuffle-left",
    categoryId: "dodgeBox",
    labelEn: "Lateral shuffle left",
    labelIt: "Spostamento laterale veloce a sinistra",
    descEn: "Athletic stance, knees bent. Take two quick steps left, then recover center. Keep chest facing forward.",
    descIt: "Piedi fermi alla larghezza delle spalle, ginocchia piegate. Due passi veloci verso sinistra, poi torna al centro. Petto sempre avanti.",
  },
  {
    id: "dodge-shuffle-right",
    categoryId: "dodgeBox",
    labelEn: "Lateral shuffle right",
    labelIt: "Spostamento laterale veloce a destra",
    descEn: "Same stance, shuffle two steps to the right, feet quick and light. Hands can guard lightly at chest height.",
    descIt: "Stessa posizione: due passi veloci a destra, piedi leggeri. Puoi tenere le mani leggere davanti al petto.",
  },
  {
    id: "dodge-quick-feet",
    categoryId: "dodgeBox",
    labelEn: "Quick feet in place",
    labelIt: "Piedi veloci sul posto",
    descEn: "Stay low and tap feet rapidly under hips like hitting hot floor. Small steps; keep weight on the balls of the feet.",
    descIt: "Resta un po’ basso sulle gambe e batti rapidamente i piedi sotto il bacino. Passi piccoli, peso sulle punte dei piedi.",
  },
  {
    id: "dodge-squat-left",
    categoryId: "dodgeBox",
    labelEn: "Half squat dodge left",
    labelIt: "Semi-accosciata e schivata a sinistra",
    descEn: "Half squat, shift hips slightly left as if slipping a rope, return center. Keep spine neutral, no collapsing forward.",
    descIt: "Semi-accosciata, sposta leggermente i fianchi a sinistra come per schivare qualcosa, torna al centro. Schiena neutra.",
  },
  {
    id: "dodge-squat-right",
    categoryId: "dodgeBox",
    labelEn: "Half squat dodge right",
    labelIt: "Semi-accosciata e schivata a destra",
    descEn: "Half squat, slip hips to the right, back to center. Move small and sharp—quality over range.",
    descIt: "Semi-accosciata, schivata verso destra, ritorno al centro. Movimento piccolo e deciso.",
  },
  {
    id: "dodge-slip-weave",
    categoryId: "dodgeBox",
    labelEn: "Slip and weave step",
    labelIt: "Schivate alternate del busto",
    descEn: "Soft knees, imagine a line at shoulder height: slip head and torso side-to-side under it, stepping slightly with each weave.",
    descIt: "Ginocchia morbide, immagina una corda all’altezza delle spalle: muovi testa e busto a destra e sinistra come per passare sotto, con un piccolo passo ogni volta.",
  },
  {
    id: "dodge-drop-step",
    categoryId: "dodgeBox",
    labelEn: "Drop step back",
    labelIt: "Passo indietro rapido",
    descEn: "From an athletic stance, step one foot back quickly and lightly, then return. Alternate legs if it feels good.",
    descIt: "Posizione bassa e pronta: fai un passo indietro veloce e leggero, poi torna. Alterna la gamba se ti è comodo.",
  },
  {
    id: "dodge-pivot-quarter",
    categoryId: "dodgeBox",
    labelEn: "Pivot steps quarter turn",
    labelIt: "Rotazione sul posto (quarto di giro)",
    descEn: "Step forward lightly, pivot on the ball of the foot 90°, recover. Alternate lead legs.",
    descIt: "Passo avanti leggero, ruota sul avampiede di novanta gradi, recupera la posizione. Alterna la gamba davanti.",
  },
  {
    id: "dodge-double-tap",
    categoryId: "dodgeBox",
    labelEn: "Double foot tap",
    labelIt: "Doppio battito dei piedi",
    descEn: "Two rapid taps with one foot then switch—stay balanced on the standing leg.",
    descIt: "Due battiti veloci sul pavimento con un piede, poi cambia; resta stabile sulla gamba di appoggio.",
  },
  {
    id: "dodge-head-bob",
    categoryId: "dodgeBox",
    labelEn: "Protective head movement drill",
    labelIt: "Movimenti di testa difensivi leggeri",
    descEn: "Hands relaxed near cheeks for awareness only. Nod yes gently, then small slips side-to-side—no snapping.",
    descIt: "Mani leggere vicino alle guance solo per consapevolezza. Muovi la testa su e giù dolcemente, poi piccole schivate laterali senza scatti bruschi.",
  },

  // ----- Core -----
  {
    id: "core-dead-bug",
    categoryId: "core",
    labelEn: "Dead bug",
    labelIt: "Supino: braccia e gambe alternate",
    descEn: "Lie on back if you can; otherwise march with ribs down. Arms up 90°, opposite arm and leg extend slowly, switch.",
    descIt: "Sdraiati sulla schiena se puoi; altrimenti marcia sul posto tenendo la zona centrale del busto ferma. Braccia a novanta gradi, estendi lentamente braccio e gamba opposti, alterna.",
  },
  {
    id: "core-bird-dog",
    categoryId: "core",
    labelEn: "Bird dog",
    labelIt: "Quadrupede allungato",
    descEn: "On hands and knees, extend opposite arm and leg level with back, hold a breath, switch. Keep hips square.",
    descIt: "A mani e ginocchia, allunga braccio e gamba opposti in linea con la schiena, tieni una respirazione, cambia. Evita che i fianchi ruotino.",
  },
  {
    id: "core-standing-bicycle",
    categoryId: "core",
    labelEn: "Standing slow bicycle",
    labelIt: "Bici in piedi lenta",
    descEn: "Hands behind head lightly. Lift knee and rotate opposite elbow toward it slowly—small range is fine.",
    descIt: "Mani leggere dietro la nuca. Solleva un ginocchio e avvicina lentamente il gomito opposto con una piccola rotazione del busto.",
  },
  {
    id: "core-side-bend",
    categoryId: "core",
    labelEn: "Standing side bends",
    labelIt: "Piegamenti laterali in piedi",
    descEn: "Arms overhead or one hand on hip. Slide into a side bend, return tall, switch sides.",
    descIt: "Braccia sopra la testa oppure una mano sul fianco. Piega il busto lateralmente, torna eretto, cambia lato.",
  },
  {
    id: "core-plank-tap",
    categoryId: "core",
    labelEn: "High plank shoulder taps",
    labelIt: "Plancia alta — tocco alle spalle",
    descEn: "Plank on floor or hands on a sturdy chair seat. Tap opposite shoulder without rocking hips. Slow reps.",
    descIt: "Plancia a terra o mani sul bordo stabile di una sedia. Tocca la spalla opposta senza far ballare i fianchi. Movimento lento.",
  },
  {
    id: "core-dead-bug-standing",
    categoryId: "core",
    labelEn: "Standing dead bug march",
    labelIt: "Marcia alternata ginocchio e braccio opposti, busto fermo",
    descEn: "Stand tall, press ribs down. Raise one knee and opposite arm overhead slowly, switch—tiny torso sway only.",
    descIt: "In piedi eretto, tieni le costole verso il basso. Solleva ginocchio e braccio opposto sopra la testa lentamente, alterna. Minimo movimento del busto.",
  },
  {
    id: "core-hollow-prep",
    categoryId: "core",
    labelEn: "Hollow hold prep (standing crunch)",
    labelIt: "Preparazione “corpo cavo” in piedi",
    descEn: "Brace abs gently, round slightly by curling ribs toward hips without collapsing neck. Release and repeat.",
    descIt: "Contrai dolcemente la zona addominale, arrotonda leggermente portando le costole verso il bacino senza schiacciare il collo. Rilascia e ripeti.",
  },
  {
    id: "core-slow-climber",
    categoryId: "core",
    labelEn: "Slow mountain climbers",
    labelIt: "Scalatore lento",
    descEn: "High plank or inclined on chair. Bring knee toward chest slowly, return, alternate. Hips stay low.",
    descIt: "Plancia alta o inclinata sulla sedia. Porta il ginocchio verso il petto lentamente, torna, alterna. Fianchi bassi e stabili.",
  },

  // ----- Mobility -----
  {
    id: "mobility-ankle-l",
    categoryId: "mobility",
    labelEn: "Ankle circles — left",
    labelIt: "Cerchi di caviglia — sinistra",
    descEn: "Lift left foot slightly. Circle the ankle smoothly both directions. Switch halfway.",
    descIt: "Solleva leggermente il piede sinistro. Ruota la caviglia con cerchi morbidi; cambia direzione a metà tempo.",
  },
  {
    id: "mobility-ankle-r",
    categoryId: "mobility",
    labelEn: "Ankle circles — right",
    labelIt: "Cerchi di caviglia — destra",
    descEn: "Lift right foot slightly. Draw circles with the ankle—keep knee still.",
    descIt: "Solleva il piede destro. Cerchi con la caviglia tenendo fermo il ginocchio.",
  },
  {
    id: "mobility-hip-circle",
    categoryId: "mobility",
    labelEn: "Hip circles",
    labelIt: "Cerchi con i fianchi",
    descEn: "Hands on hips. Circle hips like a hula hoop—both directions for half the time each.",
    descIt: "Mani sui fianchi. Disegna cerchi con il bacino come un cerchio immaginario; cambia direzione a metà tempo.",
  },
  {
    id: "mobility-wrist-wave",
    categoryId: "mobility",
    labelEn: "Wrist flex and extend waves",
    labelIt: "Onde di polso (flessione e estensione)",
    descEn: "Arms forward, gently flex wrists down and up in a flowing wave. Keep elbows quiet.",
    descIt: "Braccia avanti. Piega e stendi i polsi su e giù come un’onda fluida. Gomiti fermi.",
  },
  {
    id: "mobility-cat-cow-stand",
    categoryId: "mobility",
    labelEn: "Standing rounded and open back",
    labelIt: "Schiena arrotondata e aperta (in piedi)",
    descEn: "Hands on thighs. Round mid-back, then gently extend chest and look slightly up within comfort.",
    descIt: "Mani sulle cosce. Arrotonda la schiena al centro, poi apri delicatamente il petto e guarda leggermente in alto senza forzare.",
  },
  {
    id: "mobility-neck-slide",
    categoryId: "mobility",
    labelEn: "Gentle neck slides",
    labelIt: "Scivolamenti delicati del collo",
    descEn: "Ear toward shoulder without lifting shoulder—tiny side bends only. No full circles if that bothers you.",
    descIt: "Avvicina l’orecchio alla spalla senza alzare la spalla—solo piccoli piegamenti laterali. Evita cerchi completi se il collo fa male.",
  },
  {
    id: "mobility-thoracic-reach",
    categoryId: "mobility",
    labelEn: "Thoracic rotation reach",
    labelIt: "Rotazione alta della schiena con braccio",
    descEn: "Arm across chest, rotate open reaching to the side wall, follow hand with eyes gently. Switch arms.",
    descIt: "Braccio incrociato sul petto, ruota aprendo e allunga il braccio verso il lato seguendo la mano con lo sguardo. Cambia braccio.",
  },
  {
    id: "mobility-calf-pump",
    categoryId: "mobility",
    labelEn: "Calf raise pumps",
    labelIt: "Pompe sui polpacci",
    descEn: "Rise onto toes slowly, lower heels below flat if safe, repeat with control near a wall.",
    descIt: "Saliti sulle punte lentamente, poi abbassa i talloni verso il pavimento se ti è comodo. Ripeti vicino al muro per equilibrio.",
  },
  {
    id: "mobility-shoulder-floss",
    categoryId: "mobility",
    labelEn: "Shoulder flossing (towel optional)",
    labelIt: "Mobilità delle spalle (asciugamano opzionale)",
    descEn: "Hold a towel wide or clasp hands. Slowly lift arms overhead and back as far as comfortable without pain.",
    descIt: "Tieni un asciugamano largo tra le mani oppure unisci le mani. Alza lentamente le braccia sopra la testa e indietro fin dove è comodo, senza dolore.",
  },
  {
    id: "mobility-figure4-stand",
    categoryId: "mobility",
    labelEn: "Standing figure-four stretch assist",
    labelIt: "Stiramento figura quattro (aiutato in piedi)",
    descEn: "Cross ankle over opposite knee slightly, sit hips back a little for a gentle hip stretch. Switch legs.",
    descIt: "Incrocia la caviglia sulla ginocchia opposta leggermente, spingi indietro i fianchi un po’ per uno stiramento delicato dell’anca. Cambia gamba.",
  },

  // ----- Light cardio -----
  {
    id: "cardio-rope-ghost",
    categoryId: "cardio",
    labelEn: "Imaginary jump rope",
    labelIt: "Corda immaginaria",
    descEn: "Pretend to skip rope with small hops and wrist circles. Stay light on feet.",
    descIt: "Fai finta di saltare la corda con piccoli saltelli e cerchi dei polsi. Piedi leggeri.",
  },
  {
    id: "cardio-skater",
    categoryId: "cardio",
    labelEn: "Skater hops side to side",
    labelIt: "Saltelli laterali tipo pattinatore",
    descEn: "Leap side to side landing on one foot with the other sweeping behind for balance—small leaps if needed.",
    descIt: "Salta lateralmente appoggiando un piede e facendo passare l’altro dietro per equilibrio. Riduci l’ampiezza se serve.",
  },
  {
    id: "cardio-fast-march",
    categoryId: "cardio",
    labelEn: "Fast march on the spot",
    labelIt: "Marcia veloce sul posto",
    descEn: "Pump arms and lift knees quickly but control breathing—stop if form falls apart.",
    descIt: "Muovi le braccia e alza le ginocchia velocemente ma controlla il respiro; fermati se perdi la tecnica.",
  },
  {
    id: "cardio-box-step",
    categoryId: "cardio",
    labelEn: "Shadow boxing steps",
    labelIt: "Passi e colpi nell’aria leggeri",
    descEn: "Light bounce, throw slow straight punches into air, move feet a little between combos—stay relaxed.",
    descIt: "Rimbalzo leggero, colpi lenti nell’aria davanti a te, muovi leggermente i piedi tra una serie e l’altra. Resta rilassato.",
  },
  {
    id: "cardio-weight-shift",
    categoryId: "cardio",
    labelEn: "Rapid side weight shifts",
    labelIt: "Spostamenti rapidi del peso",
    descEn: "Feet wide, shift hips left and right quickly like steering rhythm—knees track toes.",
    descIt: "Piedi larghi, sposta rapidamente il peso da un fianco all’altro come un ritmo; le ginocchia seguono le punte dei piedi.",
  },
  {
    id: "cardio-knee-drive-run",
    categoryId: "cardio",
    labelEn: "Running arms with knee drives",
    labelIt: "Braccia da corsa con ginocchia alte",
    descEn: "On the spot, sprint arms while lifting knees medium height—short bursts, smooth landing.",
    descIt: "Sul posto, muovi le braccia come in corsa mentre sollevi le ginocchia a media altezza. Piccole serie, atterraggio morbido.",
  },
];

export const CATEGORY_ORDER = [
  { id: "arms", labelEn: "Arms", labelIt: "Braccia" },
  { id: "shoulders", labelEn: "Shoulders", labelIt: "Spalle" },
  { id: "jumps", labelEn: "Jumps", labelIt: "Salti" },
  { id: "knees", labelEn: "Knees", labelIt: "Ginocchia e gambe" },
  { id: "fullBody", labelEn: "Full-body / balance", labelIt: "Corpo intero ed equilibrio" },
  { id: "dodgeBox", labelEn: "Dodge / agility", labelIt: "Schivate e agilità" },
  { id: "core", labelEn: "Core stability", labelIt: "Centro corpo e stabilità" },
  { id: "mobility", labelEn: "Mobility", labelIt: "Mobilità articolare" },
  { id: "cardio", labelEn: "Light cardio", labelIt: "Allenamento aerobico leggero" },
];
